use wget instead of curl

diff --git a/release.yaml b/release.yaml
--- a/release.yaml
+++ b/release.yaml
@@ -8,6 +8,9 @@ inputs:
   - releaseId: server
 
 requirements:
+  # We use wget here, because curl --fail-with-body was introduced in a version ulterior to what we can have on the CI agents.
+  - name: "wget"
+    cmd: "wget --help"
   - name: "Github CLI"
     cmd: gh version
     fixInstructions: brew install gh
@@ -176,11 +179,11 @@ internal:
         cmd: |
           echo "Registering internal deploy-sourcegraph-k8s {{version}} release on release registry"
           COMMIT_SHA=$(git rev-parse HEAD)
-          body=$(curl -s --fail-with-body -X POST "https://releaseregistry.sourcegraph.com/v1/releases" -H "Content-Type: application/json" -H "Authorization: ${RELEASE_REGISTRY_TOKEN}" -d '{
+          body=$(wget --content-on-error -O- --header="Content-Type: application/json" --header="Authorization: ${RELEASE_REGISTRY_TOKEN}" --post-data '{
               "name": "k8s",
               "version": "{{version}}",
-              "git_sha": "${COMMIT_SHA}"
-            }')
+              "git_sha": "'${COMMIT_SHA}'"
+            }' "https://releaseregistry.sourcegraph.com/v1/releases")
           exit_code=$?
 
           if [ $exit_code != 0 ]; then
@@ -275,6 +278,25 @@ promoteToPublic:
           echo "🚢 Please check the associated CI build to ensure the process completed".
   finalize:
     steps:
+      - name: 'validate promotion criteria'
+        cmd: |
+          echo "validating promotion criteria"
+          body=$(wget --content-on-error -O- --header="Content-Type: application/json" "https://releaseregistry.sourcegraph.com/v1/releases/k8s/{{version}}")
+          exit_code=$?
+
+          if [ $exit_code != 0 ]; then
+            echo "❌ Failed to fetch release on release registry, got:"
+            echo "--- raw body ---"
+            echo $body
+            echo "--- raw body ---"
+            exit $exit_code
+          fi
+
+          is_development=$(echo "$body" | jq -r '.is_development')
+          if [ "$is_development" = "true" ]; then
+            echo "cannot promote a development release"
+            exit 1
+          fi
       - name: git:tag
         cmd: |
           set -eu
@@ -313,17 +335,17 @@ promoteToPublic:
       - name: 'Promote on release registry'
         cmd: |
           echo "Promoting deploy-sourcegraph-k8s {{version}} release on release registry"
-            body=$(curl -s --fail-with-body -X POST "https://releaseregistry.sourcegraph.com/v1/releases/k8s/{{version}}/promote" -H "Content-Type: application/json" -H "Authorization: ${RELEASE_REGISTRY_TOKEN}")
-            exit_code=$?
+          body=$(wget --content-on-error -O- --header="Content-Type: application/json" --header="Authorization: ${RELEASE_REGISTRY_TOKEN}" --post-data '' "https://releaseregistry.sourcegraph.com/v1/releases/k8s/{{version}}/promote")
+          exit_code=$?
 
-            if [ $exit_code != 0 ]; then
-              echo "❌ Failed to promote release on release registry, got:"
-              echo "--- raw body ---"
-              echo $body
-              echo "--- raw body ---"
-              exit $exit_code
-            else
-              echo "Release promoted, see:"
-              echo $body | jq .web_url
-            fi
+          if [ $exit_code != 0 ]; then
+            echo "❌ Failed to promote release on release registry, got:"
+            echo "--- raw body ---"
+            echo $body
+            echo "--- raw body ---"
+            exit $exit_code
+          else
+            echo "Build created, see:"
+            echo $body | jq .web_url
+          fi
 
